/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __Av2HR_ADM_POI_LIST_hpp__
#define __Av2HR_ADM_POI_LIST_hpp__

#include <vector>
#include "Av2HR_ADM_POI.hpp"


class Av2HR_ADM_POI_LIST
{
    public:
        int64_t    m_tmSinceEpoch;
        int32_t    m_iPathIndex;
        int32_t    m_iOffset;
        int16_t    m_iPOINum;
        std::vector< Av2HR_ADM_POI > m_poiList;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int Av2HR_ADM_POI_LIST::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int Av2HR_ADM_POI_LIST::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Av2HR_ADM_POI_LIST::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t Av2HR_ADM_POI_LIST::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* Av2HR_ADM_POI_LIST::getTypeName()
{
    return "Av2HR_ADM_POI_LIST";
}

int Av2HR_ADM_POI_LIST::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->m_tmSinceEpoch, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->m_iPathIndex, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->m_iOffset, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->m_iPOINum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->m_iPOINum; a0++) {
        tlen = this->m_poiList[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int Av2HR_ADM_POI_LIST::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->m_tmSinceEpoch, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->m_iPathIndex, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->m_iOffset, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->m_iPOINum, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->m_poiList.resize(this->m_iPOINum);
    for (int a0 = 0; a0 < this->m_iPOINum; a0++) {
        tlen = this->m_poiList[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int Av2HR_ADM_POI_LIST::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->m_iPOINum; a0++) {
        enc_size += this->m_poiList[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t Av2HR_ADM_POI_LIST::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == Av2HR_ADM_POI_LIST::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)Av2HR_ADM_POI_LIST::getHash };

    int64_t hash = 0x2fbec5fec33e0716LL +
         Av2HR_ADM_POI::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
