/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __LCM_VELODYNE_CLOUD_POINT_hpp__
#define __LCM_VELODYNE_CLOUD_POINT_hpp__

#include <vector>
#include "LCM_POINT2D_F.hpp"


class LCM_VELODYNE_CLOUD_POINT
{
    public:
        int8_t     nDevType;
        int64_t    nFrameId;
        int64_t    nTimeStamp;
        int32_t    nPointCont;
        std::vector< LCM_POINT2D_F > CloudPoint;

    public:
		inline void LCM_VELODYNE_CLOUD_POINT();
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

void LCM_VELODYNE_CLOUD_POINT::LCM_VELODYNE_CLOUD_POINT()
{
	nDevType = 0;
	nFrameId = 0;
	nTimeStamp = 0;
	nPointCont = 0;
	CloudPoint.clear();
}

int LCM_VELODYNE_CLOUD_POINT::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LCM_VELODYNE_CLOUD_POINT::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LCM_VELODYNE_CLOUD_POINT::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t LCM_VELODYNE_CLOUD_POINT::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* LCM_VELODYNE_CLOUD_POINT::getTypeName()
{
    return "LCM_VELODYNE_CLOUD_POINT";
}

int LCM_VELODYNE_CLOUD_POINT::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->nDevType, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->nFrameId, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->nTimeStamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->nPointCont, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->nPointCont; a0++) {
        tlen = this->CloudPoint[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LCM_VELODYNE_CLOUD_POINT::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->nDevType, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->nFrameId, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->nTimeStamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->nPointCont, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->CloudPoint.resize(this->nPointCont);
    for (int a0 = 0; a0 < this->nPointCont; a0++) {
        tlen = this->CloudPoint[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LCM_VELODYNE_CLOUD_POINT::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->nPointCont; a0++) {
        enc_size += this->CloudPoint[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t LCM_VELODYNE_CLOUD_POINT::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == LCM_VELODYNE_CLOUD_POINT::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)LCM_VELODYNE_CLOUD_POINT::getHash };

    int64_t hash = 0x1405e23eaf13cc9cLL +
         LCM_POINT2D_F::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
