/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __LCM_IBEO_OBJECT_LIST_hpp__
#define __LCM_IBEO_OBJECT_LIST_hpp__

#include <vector>
#include "LCM_IBEO_OBJECT.hpp"
#include "LCM_GPS_DATA.hpp"


class LCM_IBEO_OBJECT_LIST
{
    public:
        int64_t    TimeStamp;
        int64_t    FrameInd;
        int8_t     DevInd;
        int8_t     DevType;
        int64_t    ContObjects;
        std::vector< LCM_IBEO_OBJECT > IbeoObjects;
        LCM_GPS_DATA GpsData;

    public:
		inline LCM_IBEO_OBJECT_LIST();
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

LCM_IBEO_OBJECT_LIST::LCM_IBEO_OBJECT_LIST()
{
	ContObjects = 0;
	IbeoObjects.clear();
}

int LCM_IBEO_OBJECT_LIST::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LCM_IBEO_OBJECT_LIST::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LCM_IBEO_OBJECT_LIST::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t LCM_IBEO_OBJECT_LIST::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* LCM_IBEO_OBJECT_LIST::getTypeName()
{
    return "LCM_IBEO_OBJECT_LIST";
}

int LCM_IBEO_OBJECT_LIST::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->TimeStamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->FrameInd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->DevInd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->DevType, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->ContObjects, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->ContObjects; a0++) {
        tlen = this->IbeoObjects[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->GpsData._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LCM_IBEO_OBJECT_LIST::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->TimeStamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->FrameInd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->DevInd, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->DevType, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->ContObjects, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->IbeoObjects.resize(this->ContObjects);
    for (int a0 = 0; a0 < this->ContObjects; a0++) {
        tlen = this->IbeoObjects[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = this->GpsData._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LCM_IBEO_OBJECT_LIST::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->ContObjects; a0++) {
        enc_size += this->IbeoObjects[a0]._getEncodedSizeNoHash();
    }
    enc_size += this->GpsData._getEncodedSizeNoHash();
    return enc_size;
}

int64_t LCM_IBEO_OBJECT_LIST::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == LCM_IBEO_OBJECT_LIST::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)LCM_IBEO_OBJECT_LIST::getHash };

    int64_t hash = 0xc79d89d8dad265e4LL +
         LCM_IBEO_OBJECT::_computeHash(&cp) +
         LCM_GPS_DATA::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
