/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __LIDAR_RADAR_INFO_hpp__
#define __LIDAR_RADAR_INFO_hpp__

#include "LIDAR_RADAR_OBJECT_INFO.hpp"


class LIDAR_RADAR_INFO
{
    public:
        int32_t    nLidarRadarType;
        LIDAR_RADAR_OBJECT_INFO Objects[64];

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int LIDAR_RADAR_INFO::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LIDAR_RADAR_INFO::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LIDAR_RADAR_INFO::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t LIDAR_RADAR_INFO::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* LIDAR_RADAR_INFO::getTypeName()
{
    return "LIDAR_RADAR_INFO";
}

int LIDAR_RADAR_INFO::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->nLidarRadarType, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 64; a0++) {
        tlen = this->Objects[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LIDAR_RADAR_INFO::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->nLidarRadarType, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < 64; a0++) {
        tlen = this->Objects[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LIDAR_RADAR_INFO::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < 64; a0++) {
        enc_size += this->Objects[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

int64_t LIDAR_RADAR_INFO::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == LIDAR_RADAR_INFO::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)LIDAR_RADAR_INFO::getHash };

    int64_t hash = 0xe0068f7527dbc617LL +
         LIDAR_RADAR_OBJECT_INFO::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
